import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1e293b',
    letterSpacing: 1,
  },
  searchInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  petCount: {
    fontSize: 14,
    color: '#94a3b8',
    marginBottom: 12,
  },
  card: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 14,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  petName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0f172a',
  },
  petSubtitle: {
    color: '#64748b',
    marginTop: 2,
    fontSize: 14,
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: 60,
  },
  emptyEmoji: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#94a3b8',
  },
  emptySubtext: {
    color: '#94a3b8',
    marginTop: 8,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#334155',
  },
  value: {
    fontSize: 16,
    color: '#0f172a',
    flex: 1,
    textAlign: 'right',
    marginLeft: 10,
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    paddingTop: 8,
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    flex: 1,
    color: '#0f172a',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 12,
    marginTop: 8,
  },
  bioCard: {
    backgroundColor: '#f1f5f9',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  bioText: {
    color: '#475569',
    fontSize: 16,
    lineHeight: 24,
  },
  playdateButton: {
    backgroundColor: '#2563eb',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  playdateButtonActive: {
    backgroundColor: '#22c55e',
    shadowColor: '#22c55e',
  },
  playdateButtonText: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  matchScoreContainer: {
    marginTop: 20,
    paddingVertical: 14,
    borderTopWidth: 2,
    borderTopColor: '#e2e8f0',
    alignItems: 'center',
  },
  matchScoreLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#334155',
  },
  matchScoreNumber: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#16a34a',
    marginTop: 4,
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  settingLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1e293b',
  },
  settingInput: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 16,
    width: 160,
    textAlign: 'right',
    backgroundColor: '#ffffff',
  },
  settingsFooter: {
    marginTop: 40,
    alignItems: 'center',
  },
  welcomeText: {
    fontSize: 14,
    color: '#64748b',
  },
  versionText: {
    color: '#94a3b8',
    fontSize: 12,
    marginTop: 4,
  },
  backButton: {
    marginTop: 20,
    backgroundColor: '#2563eb',
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 10,
    alignItems: 'center',
  },
  backButtonText: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});